export interface AceternityComponent {
  slug: string;
  name: string;
  description: string;
  url: string;
}

export const aceternityRegistry: AceternityComponent[] = [
  { slug: "3d-card-effect", name: "3D Card Effect", description: "A card with a 3D tilt effect on hover.", url: "https://ui.aceternity.com/components/3d-card-effect" },
  { slug: "3d-marquee", name: "3D Marquee", description: "A 3D marquee effect for scrolling content.", url: "https://ui.aceternity.com/components/3d-marquee" },
  { slug: "3d-pin", name: "3D Animated Pin", description: "A 3D animated pin component for map-like interactions.", url: "https://ui.aceternity.com/components/3d-pin" },
  { slug: "animated-modal", name: "Animated Modal", description: "A modal with smooth open/close animations.", url: "https://ui.aceternity.com/components/animated-modal" },
  { slug: "animated-tabs", name: "Animated Tabs", description: "Tabs with smooth animated transitions.", url: "https://ui.aceternity.com/components/tabs" },
  { slug: "animated-testimonials", name: "Animated Testimonials", description: "Testimonial cards with animated transitions.", url: "https://ui.aceternity.com/components/animated-testimonials" },
  { slug: "animated-tooltip", name: "Animated Tooltip", description: "A tooltip with animated entrance effects.", url: "https://ui.aceternity.com/components/animated-tooltip" },
  { slug: "apple-cards-carousel", name: "Apple Cards Carousel", description: "A carousel inspired by Apple's card design.", url: "https://ui.aceternity.com/components/apple-cards-carousel" },
  { slug: "aurora-background", name: "Aurora Background", description: "A mesmerizing aurora borealis background effect.", url: "https://ui.aceternity.com/components/aurora-background" },
  { slug: "background-beams", name: "Background Beams", description: "Animated beam lines in the background.", url: "https://ui.aceternity.com/components/background-beams" },
  { slug: "background-beams-with-collision", name: "Background Beams With Collision", description: "Beams that collide and interact with each other.", url: "https://ui.aceternity.com/components/background-beams-with-collision" },
  { slug: "background-boxes", name: "Background Boxes", description: "Grid of animated boxes in the background.", url: "https://ui.aceternity.com/components/background-boxes" },
  { slug: "background-gradient", name: "Background Gradient", description: "A smooth animated gradient background.", url: "https://ui.aceternity.com/components/background-gradient" },
  { slug: "background-gradient-animation", name: "Background Gradient Animation", description: "An animated gradient that shifts colors smoothly.", url: "https://ui.aceternity.com/components/background-gradient-animation" },
  { slug: "background-lines", name: "Background Lines", description: "Animated lines moving in the background.", url: "https://ui.aceternity.com/components/background-lines" },
  { slug: "background-ripple-effect", name: "Background Ripple Effect", description: "A ripple animation effect in the background.", url: "https://ui.aceternity.com/components/background-ripple-effect" },
  { slug: "bento-grid", name: "Bento Grid", description: "A bento-style grid layout for content.", url: "https://ui.aceternity.com/components/bento-grid" },
  { slug: "canvas-reveal-effect", name: "Canvas Reveal Effect", description: "A canvas-based reveal animation effect.", url: "https://ui.aceternity.com/components/canvas-reveal-effect" },
  { slug: "card-hover-effect", name: "Card Hover Effect", description: "Cards with interactive hover animations.", url: "https://ui.aceternity.com/components/card-hover-effect" },
  { slug: "card-spotlight", name: "Card Spotlight", description: "A card with a spotlight effect following the cursor.", url: "https://ui.aceternity.com/components/card-spotlight" },
  { slug: "card-stack", name: "Card Stack", description: "A stack of cards with swipe interactions.", url: "https://ui.aceternity.com/components/card-stack" },
  { slug: "carousel", name: "Carousel", description: "An animated carousel component.", url: "https://ui.aceternity.com/components/carousel" },
  { slug: "code-block", name: "Code Block", description: "A styled code block with syntax highlighting.", url: "https://ui.aceternity.com/components/code-block" },
  { slug: "colourful-text", name: "Colourful Text", description: "Text with colorful animated gradients.", url: "https://ui.aceternity.com/components/colourful-text" },
  { slug: "comet-card", name: "Comet Card", description: "A card with a comet trail border effect.", url: "https://ui.aceternity.com/components/comet-card" },
  { slug: "compare", name: "Compare", description: "A before/after image comparison slider.", url: "https://ui.aceternity.com/components/compare" },
  { slug: "container-cover", name: "Cover", description: "A container with a cover animation effect.", url: "https://ui.aceternity.com/components/container-cover" },
  { slug: "container-scroll-animation", name: "Container Scroll Animation", description: "Scroll-triggered container animations.", url: "https://ui.aceternity.com/components/container-scroll-animation" },
  { slug: "container-text-flip", name: "Container Text Flip", description: "A text flip animation within a container.", url: "https://ui.aceternity.com/components/container-text-flip" },
  { slug: "direction-aware-hover", name: "Direction Aware Hover", description: "Hover effect that responds to cursor direction.", url: "https://ui.aceternity.com/components/direction-aware-hover" },
  { slug: "dither-shader", name: "Dither Shader", description: "A dithering shader effect for images.", url: "https://ui.aceternity.com/components/dither-shader" },
  { slug: "dotted-glow-background", name: "Dotted Glow Background", description: "A dotted background with a glowing effect.", url: "https://ui.aceternity.com/components/dotted-glow-background" },
  { slug: "draggable-card", name: "Draggable Card", description: "A card that can be dragged around the screen.", url: "https://ui.aceternity.com/components/draggable-card" },
  { slug: "encrypted-text", name: "Encrypted Text", description: "Text with a scramble/decrypt animation effect.", url: "https://ui.aceternity.com/components/encrypted-text" },
  { slug: "evervault-card", name: "Evervault Card", description: "A card inspired by Evervault's design.", url: "https://ui.aceternity.com/components/evervault-card" },
  { slug: "expandable-card", name: "Expandable Cards", description: "Cards that expand to reveal more content.", url: "https://ui.aceternity.com/components/expandable-card" },
  { slug: "file-upload", name: "File Upload", description: "A styled file upload component with animations.", url: "https://ui.aceternity.com/components/file-upload" },
  { slug: "flip-words", name: "Flip Words", description: "Words that flip and change with animation.", url: "https://ui.aceternity.com/components/flip-words" },
  { slug: "floating-dock", name: "Floating Dock", description: "A macOS-style floating dock component.", url: "https://ui.aceternity.com/components/floating-dock" },
  { slug: "floating-navbar", name: "Floating Navbar", description: "A navbar that floats and animates on scroll.", url: "https://ui.aceternity.com/components/floating-navbar" },
  { slug: "focus-cards", name: "Focus Cards", description: "Cards that blur others when one is focused.", url: "https://ui.aceternity.com/components/focus-cards" },
  { slug: "following-pointer", name: "Following Pointer", description: "An element that follows the mouse pointer.", url: "https://ui.aceternity.com/components/following-pointer" },
  { slug: "github-globe", name: "GitHub Globe", description: "A 3D globe inspired by GitHub's design.", url: "https://ui.aceternity.com/components/github-globe" },
  { slug: "glare-card", name: "Glare Card", description: "A card with a glare effect on hover.", url: "https://ui.aceternity.com/components/glare-card" },
  { slug: "glowing-effect", name: "Glowing Effect", description: "A glowing border/outline effect.", url: "https://ui.aceternity.com/components/glowing-effect" },
  { slug: "glowing-stars-effect", name: "Glowing Background Stars Card", description: "A card with glowing stars in the background.", url: "https://ui.aceternity.com/components/glowing-stars-effect" },
  { slug: "google-gemini-effect", name: "Google Gemini Effect", description: "An effect inspired by Google Gemini's design.", url: "https://ui.aceternity.com/components/google-gemini-effect" },
  { slug: "grid-and-dot-backgrounds", name: "Grid and Dot Backgrounds", description: "Customizable grid and dot pattern backgrounds.", url: "https://ui.aceternity.com/components/grid-and-dot-backgrounds" },
  { slug: "hero-highlight", name: "Hero Highlight", description: "A hero section with animated highlight effects.", url: "https://ui.aceternity.com/components/hero-highlight" },
  { slug: "hero-parallax", name: "Hero Parallax", description: "A hero section with parallax scrolling effect.", url: "https://ui.aceternity.com/components/hero-parallax" },
  { slug: "hover-border-gradient", name: "Hover Border Gradient", description: "A gradient border that animates on hover.", url: "https://ui.aceternity.com/components/hover-border-gradient" },
  { slug: "images-badge", name: "Images Badge", description: "Badges with image avatars.", url: "https://ui.aceternity.com/components/images-badge" },
  { slug: "images-slider", name: "Images Slider", description: "A smooth image slider component.", url: "https://ui.aceternity.com/components/images-slider" },
  { slug: "infinite-moving-cards", name: "Infinite Moving Cards", description: "Cards that scroll infinitely in a loop.", url: "https://ui.aceternity.com/components/infinite-moving-cards" },
  { slug: "keyboard", name: "Keyboard", description: "An animated keyboard component.", url: "https://ui.aceternity.com/components/keyboard" },
  { slug: "lamp-effect", name: "Lamp Section Header", description: "A section header with a lamp lighting effect.", url: "https://ui.aceternity.com/components/lamp-effect" },
  { slug: "layout-grid", name: "Layout Grid", description: "An interactive layout grid with expandable items.", url: "https://ui.aceternity.com/components/layout-grid" },
  { slug: "layout-text-flip", name: "Layout Text Flip", description: "A layout with flipping text animations.", url: "https://ui.aceternity.com/components/layout-text-flip" },
  { slug: "lens", name: "Lens", description: "A magnifying lens effect for images.", url: "https://ui.aceternity.com/components/lens" },
  { slug: "link-preview", name: "Link Preview", description: "A link that shows a preview on hover.", url: "https://ui.aceternity.com/components/link-preview" },
  { slug: "loader", name: "Loaders", description: "Animated loading indicators.", url: "https://ui.aceternity.com/components/loader" },
  { slug: "macbook-scroll", name: "Macbook Scroll", description: "A MacBook-style scroll animation.", url: "https://ui.aceternity.com/components/macbook-scroll" },
  { slug: "meteors", name: "Meteor Effect", description: "Animated meteors falling in the background.", url: "https://ui.aceternity.com/components/meteors" },
  { slug: "moving-border", name: "Moving Border", description: "A border that moves around an element.", url: "https://ui.aceternity.com/components/moving-border" },
  { slug: "multi-step-loader", name: "Multi Step Loader", description: "A loader that shows multiple loading steps.", url: "https://ui.aceternity.com/components/multi-step-loader" },
  { slug: "navbar-menu", name: "Navbar Menu", description: "An animated navbar menu component.", url: "https://ui.aceternity.com/components/navbar-menu" },
  { slug: "noise-background", name: "Noise Background", description: "A background with animated noise texture.", url: "https://ui.aceternity.com/components/noise-background" },
  { slug: "parallax-scroll", name: "Parallax Grid Scroll", description: "A grid layout with parallax scroll effect.", url: "https://ui.aceternity.com/components/parallax-scroll" },
  { slug: "pixelated-canvas", name: "Pixelated Canvas", description: "A canvas with pixelation effects.", url: "https://ui.aceternity.com/components/pixelated-canvas" },
  { slug: "placeholders-and-vanish-input", name: "Placeholders And Vanish Input", description: "An input with animated placeholders that vanish.", url: "https://ui.aceternity.com/components/placeholders-and-vanish-input" },
  { slug: "pointer-highlight", name: "Pointer Highlight", description: "A highlight effect that follows the pointer.", url: "https://ui.aceternity.com/components/pointer-highlight" },
  { slug: "resizable-navbar", name: "Resizable Navbar", description: "A navbar that resizes on scroll.", url: "https://ui.aceternity.com/components/resizable-navbar" },
  { slug: "shooting-stars-and-stars-background", name: "Shooting Stars Background", description: "A background with shooting stars animation.", url: "https://ui.aceternity.com/components/shooting-stars-and-stars-background" },
  { slug: "sidebar", name: "Sidebar", description: "An animated sidebar navigation component.", url: "https://ui.aceternity.com/components/sidebar" },
  { slug: "signup-form", name: "Signup Form", description: "A styled signup form with animations.", url: "https://ui.aceternity.com/components/signup-form" },
  { slug: "sparkles", name: "Sparkles", description: "Animated sparkle effects.", url: "https://ui.aceternity.com/components/sparkles" },
  { slug: "spotlight", name: "Spotlight", description: "A spotlight effect that follows the cursor.", url: "https://ui.aceternity.com/components/spotlight" },
  { slug: "spotlight-new", name: "Spotlight New", description: "An updated spotlight effect component.", url: "https://ui.aceternity.com/components/spotlight-new" },
  { slug: "stateful-button", name: "Stateful Button", description: "A button with animated state transitions.", url: "https://ui.aceternity.com/components/stateful-button" },
  { slug: "sticky-banner", name: "Sticky Banner", description: "A sticky banner that stays on scroll.", url: "https://ui.aceternity.com/components/sticky-banner" },
  { slug: "sticky-scroll-reveal", name: "Sticky Scroll Reveal", description: "Content that reveals as you scroll with sticky positioning.", url: "https://ui.aceternity.com/components/sticky-scroll-reveal" },
  { slug: "svg-mask-effect", name: "SVG Mask Effect", description: "An SVG-based mask reveal effect.", url: "https://ui.aceternity.com/components/svg-mask-effect" },
  { slug: "tailwindcss-buttons", name: "Tailwind CSS Buttons", description: "A collection of styled Tailwind CSS buttons.", url: "https://ui.aceternity.com/components/tailwindcss-buttons" },
  { slug: "text-generate-effect", name: "Text Generate Effect", description: "Text that generates character by character.", url: "https://ui.aceternity.com/components/text-generate-effect" },
  { slug: "text-hover-effect", name: "Text Hover Effect", description: "Text with interactive hover effects.", url: "https://ui.aceternity.com/components/text-hover-effect" },
  { slug: "text-reveal-card", name: "Text Reveal Card", description: "A card that reveals text on hover.", url: "https://ui.aceternity.com/components/text-reveal-card" },
  { slug: "timeline", name: "Timeline", description: "An animated timeline component.", url: "https://ui.aceternity.com/components/timeline" },
  { slug: "tooltip-card", name: "Tooltip Card", description: "A card-style tooltip with rich content.", url: "https://ui.aceternity.com/components/tooltip-card" },
  { slug: "tracing-beam", name: "Tracing Beam", description: "A beam that traces along content as you scroll.", url: "https://ui.aceternity.com/components/tracing-beam" },
  { slug: "typewriter-effect", name: "Typewriter Effect", description: "Text with a typewriter typing animation.", url: "https://ui.aceternity.com/components/typewriter-effect" },
  { slug: "vortex", name: "Vortex Background", description: "A vortex-style animated background.", url: "https://ui.aceternity.com/components/vortex" },
  { slug: "wavy-background", name: "Wavy Background", description: "An animated wavy background effect.", url: "https://ui.aceternity.com/components/wavy-background" },
  { slug: "webcam-pixel-grid", name: "Webcam Pixel Grid", description: "A pixelated grid effect using webcam input.", url: "https://ui.aceternity.com/components/webcam-pixel-grid" },
  { slug: "wobble-card", name: "Wobble Card", description: "A card that wobbles on hover interaction.", url: "https://ui.aceternity.com/components/wobble-card" },
  { slug: "world-map", name: "World Map", description: "An animated world map component.", url: "https://ui.aceternity.com/components/world-map" },
];
